// <auto-generated />
namespace CrmPro.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cateupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cateupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201404100335179_cateupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
