// <auto-generated />
namespace CrmPro.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class asfa2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asfa2));
        
        string IMigrationMetadata.Id
        {
            get { return "201404100333221_asfa2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
